### ISSUE TITLE
Possible to add new lines in detailed description?

### ISSUE THREAD

**Issue by peterjuras** [vivaxy/vscode-conventional-commits#10]
First of all, thanks for creating this extension, it adds a lot of value to my workflow! 🎉 🙏 

I wanted to ask whether it is possible to add new lines in the detailed description prompt, since I currently always have to `git commit --amend` afterwards to format it correctly in case I want to have new lines in between some parts.

I understand that Visual Studio Code might not allow for a multi-line prompt (I didn't check), but how about adding an identifier which translates into a new line in the commit message, e.g. `\n`?

**Comment by vivaxy** [comment]
Thank you for your feedback.

I think there is a workaround: disabling `autoCommit`.

The workflow will be:
1. Open VSCode Conventional Commits extension, enter messages.
2. Edit the formatted message in the VSCode Source Control Message box
3. Commit by using VSCode command `git.commit` or click the `√` button in Source Control panel.

I'll try to implement `\n` as line break soon.

**Comment by peterjuras** [comment]
Thanks this also works well for me! 👍

**Comment by DiogoAbu** [comment]
Thanks it works for me too, it would be nice if it could focus the message text input when the message is added.

**Comment by vivaxy** [comment]
@DiogoAbu Thanks for the suggestion, but the VSCode git extension does not provide the API to focus the message input for now.
