### ISSUE TITLE
[FEAT] Settings to remove unused options

### ISSUE THREAD

**Issue by ahinkle** [vivaxy/vscode-conventional-commits#107]
**Is your feature request related to a problem? Please describe.**
Hi, Thank you for creating this awesome extension. I've been using it for quite some time and one thing that bothers me is spamming through "enter" on sections that I _never_ complete.

For example:
- Type of change: **chore**
- Scope: **(issue number)**
- Emoji: **📝** 
- short description: **Update documentation**
- ~~longer description:~~
- ~~breaking changes:~~

**Describe the solution you'd like**
It would be nice if we could have all 6 options as a setting checkbox to define if it will appear in the 1/6 commit options with each option default set to true or checked.

it looks like we have some of the options already done (Emoji and Scopes) but it would be nice for all options.

**Describe alternatives you've considered**

**Additional context**

**Comment by yi-Xu-0100** [comment]
👋 @ahinkle Thanks for your suggestions, These options will add in the future if I have the time to do. 👍

 1. For the `emoji` and the `scope`, you can set the `conventionalCommits.gitmoji` and the `conventionalCommits.promptScopes` as false to disable them. This should have an introduction in the README, I will enhance this part. 📝
2. And the `breaking changes` will have the configuration, too. 😁
3. For the others, please be patient, I will do it! 🚧

By the way, if you have the time to complete those feature and make a PR, I will appreciate it! 😊

**Comment by yi-Xu-0100** [comment]
👋@ahinkle @vivaxy, according to the [specification](https://www.conventionalcommits.org/en/v1.0.0/#specification) of the conventional commits, I think the type and description should not remove. 😁

Any more I need to do with this issue?

**Comment by ahinkle** [comment]
Yes, completely agree there. Thank you so much! 🎉
