### ISSUE TITLE
[FEAT] "Confirm" GUI item for Description input

### ISSUE THREAD

**Issue by irvnriir** [vivaxy/vscode-conventional-commits#155]
### Is your feature request related to a problem? Please describe

Sometimes i want to simply select a preset for the commit message . If i do this using mouse, i still have to press Enter at the Description input .

### Describe the solution you'd like

The easiest way could be the same type of list item that is used for option selection at other fields .

### Additional context

Looking forward for: ability to set custom Types, from https://github.com/vivaxy/vscode-conventional-commits/issues/93 .

**Comment by yi-Xu-0100** [comment]
👋 @irvnriir Thanks for your idea!

You mean the description prompt should have selections of preset messages? In which it can be an empty selection and edit in the editor tab? 😀

>  If i do this using mouse, I still have to press Enter at the Description input.

By the way, I found it also, but I use the extension with full keyboard control now because I think that I always need to write the description in the editor tab. 😅

For the simple ways to set custom types, you can look into #137. 😁

**Comment by irvnriir** [comment]
I mean it should have 1 selection -- "Confirm" , so that could be used to skip it using mouse . The presets is to be defined as custom types or such other .

**Comment by irvnriir** [comment]
> For the simple ways to set custom types, you can look into #137. 😁

@yi-Xu-0100 seems that this doesn't work, if i'm not missing something .

![Screenshot](https://user-images.githubusercontent.com/13949704/116100477-7b611100-a69c-11eb-8242-70299e13454f.png)

Though i look into way to customize it in userfiles (not directories) .

**Comment by yi-Xu-0100** [comment]
@irvnriir Could you paste the log here?  See the workflow in [troubleshooting](https://github.com/vivaxy/vscode-conventional-commits#troubleshooting) section. 😀

**Comment by irvnriir** [comment]
@yi-Xu-0100 
```
[info] Extension Activated
[info] vscode.env.language: en
[info] last used version: 1.20.0
[info] Conventional commits started.
[info] VSCode version: 1.55.2
[info] Git version: 1.0.0
[info] VSCode Conventional Commits version: 1.20.0
[info] conventionalCommits.autoCommit: true
[info] conventionalCommits.emojiFormat: code
[info] conventionalCommits.gitmoji: false
[info] conventionalCommits.lineBreak: 
[info] conventionalCommits.promptBody: false
[info] conventionalCommits.promptFooter: false
[info] conventionalCommits.promptScopes: false
[info] conventionalCommits.scopes: 
[info] conventionalCommits.showEditor: false
[info] conventionalCommits.showNewVersionNotes: true
[info] conventionalCommits.editor.keepAfterSave: false
[info] git.enableSmartCommit: true
[info] git.smartCommitChanges: all
[info] git.postCommitCommand: none
[info] arg: undefined
[info] git.repositories: c:\Users\admin\storage\t\New folder
[info] workspaceFolders: c:\Users\admin\storage\t\New folder
[info] Load commitlint configuration successfully.
[info] commitlintRuleConfigs:
{}
```

**Comment by yi-Xu-0100** [comment]
@irvnriir This is a very strange situation, is your `package.json` saved? Does the same thing occur for restarting VS Code? Can you read the configuration directly using `commitlint`? Can you share the minimum reproduction repository?

**Comment by irvnriir** [comment]
@yi-Xu-0100 how would i "use `commitlint`" ? its unrelated to vsc, other extensions and git repository .

**Comment by yi-Xu-0100** [comment]
@irvnriir I found you use the `extends` configuration for `commitlint` setting.

```json
"commitlint": {
  "extends": [
    "@commitlint/config-conventional"
  ]
}
```

It needs the dependence of `@commitlint/config-conventional`. If you want to use the `commitlint` from terminal, just add a dependence of `@commitlint/cli`. It should read the configuration correctly. See more in [cli-documents](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/cli).

```log
[info] git.repositories: c:\Users\admin\storage\t\New folder
[info] workspaceFolders: c:\Users\admin\storage\t\New folder
[info] Load commitlint configuration successfully.
[info] commitlintRuleConfigs:
{}
```

For now, the log shows the git.repositories, and will use the path as the load path of `commitlint` configuration file. It seems to find the configuration correctly but return zero rules. I don't know why. 😅

So if you do not familiar with `commitlint`, could you provide a simple project to reproduction this situation for me to test? 🙂

**Comment by irvnriir** [comment]
@yi-Xu-0100 i don't have Commitlint npm package installed, neither want to . so its required ? i though you just use the compatible config name, and the config modify the extension's behavior, without depending on Commitlint .

**Comment by yi-Xu-0100** [comment]
@irvnriir 
For now, If you only use the configuration about rules, you will not need any package about `commitlint` because the extension should load `commitlint` configuration about rules correctly. The `extends` point to a package `@commitlint/config-conventional`, so you need it. But it should output a warning in logs if you do not have it. 👀

I will bring a configuration option about default rules later which will not need the `commitlint` configuration in `package.json`. 😀 But be patient, I am busy recently. 🚧

And the `commitlint` package is used to test locally for why it does not work, which is not necessary. If you do not want to test by yourself, or you do not know how to test. Could you provide a simple project to reproduction this situation for me to test? But you know, the log shows it works well. I may not work fail with my test. So I suggest you test in your local. 😅

**Comment by irvnriir** [comment]
@yi-Xu-0100 the extension's package.json already has all the dependencies:
```
	"dependencies": {
		"@commitlint/cli": "^12.0.0",
		"@commitlint/config-conventional": "^12.0.0",
		"@commitlint/load": "^12.0.0",
		"@commitlint/rules": "^12.0.0",
		"@yi-xu-0100/conventional-commit-types-i18n": "1.6.0",
		"gitmojis": "^3.0.0"
	},
```
i doubt that the repo init settings would affect this
[New folder.zip](https://github.com/vivaxy/vscode-conventional-commits/files/6381423/New.folder.zip)

**Comment by yi-Xu-0100** [comment]
@irvnriir I think I can not find the `package.json` in your repo. So add your configuration in your repo, not the extension path. 😅

The extension read the configuration from your repo. If you do not want to use the `package.json`, you also can use the `commitlint.config.js` in your repo.

Here is an example repo with `commitlint.config.js`.

[New folder.zip](https://github.com/vivaxy/vscode-conventional-commits/files/6381538/New.folder.zip)

**Comment by irvnriir** [comment]
@yi-Xu-0100 thats completely new info . and kind of solves alot, though userconfig is still better for this task . thanks .

**Comment by yi-Xu-0100** [comment]
@vivaxy @irvnriir, After I saw PR #183, I think I found an example of the settings button. 😁

I investigated the related API and other examples, and a forward button corresponding to the back button may be set later to confirm the operation. The GUI is like this:

![图片](https://user-images.githubusercontent.com/25523606/130314211-84f20c5f-592b-47cb-bb92-82ba52de7e7e.png)

After the PR #183 merge, I will try to implement the function of this button in my free time to solve the current issue. 😀

**Comment by yi-Xu-0100** [comment]
Thanks to @toddlerer rich implementation, I can use very little code to add a button to solve this problem. ❤

@irvnriir I complete the confirm button by [workflow-vscode-conventional-commits-6025224.vsix](https://github.com/vivaxy/vscode-conventional-commits/actions/runs/1176124162#artifacts). Try it and give your advice! 😁

@vivaxy If there is no more question about it, I will release it next friday~ 😊

**Comment by irvnriir** [comment]
@yi-Xu-0100 this seem to work with no issues, and minimally does close this issue .

it still would be good to see ability to just select a preset, without need to further move the mouse and click . for example a setting to disable the editbox/"description" part . (so after selecting the preset/-s, the frame would close automatically)
* if `autoCommit` is disabled, after the preset/-s selection it would be intended to write in the Sidebar\\Source Control 's editbox, which allow to edit the text before and after the preset/-s ;
* after selecting preset/-s, the `Sidebar\Source Control\Commit` button can be used if no additional text is needed .

**Comment by yi-Xu-0100** [comment]
@irvnriir I do not think the preset for the description of the commit is good. The same commit message is terrible. 😅 

I can provide a configuration as `conventionalCommits.promptDescription` to disable the `description` section. But it will only work when the `conventionalCommits.autoCommit` setting to false **or** the `conventionalCommits.showEditor` setting to true. 😀

@vivaxy  What do you think of this feature? 🧐

**Comment by vivaxy** [comment]
@irvnriir @yi-Xu-0100 I think we need more detailed information to come to a conclusion about this `preset` feature. It could be better if we could talk about this in another issue thread.

**Comment by irvnriir** [comment]
@yi-Xu-0100 this still would be an improvement .

you can't know whats better per each project in the world .

**Comment by yi-Xu-0100** [comment]
@irvnriir `conventionalCommits.promptDescription` is also good for edit commit in a separate tab. See in the #189. 😁

@vivaxy The confirm button has been added! And will release on next Friday! 🎉

**Comment by vivaxy** [comment]
@irvnriir That's an interesting topic. Maybe we talk more about it in https://github.com/vivaxy/vscode-conventional-commits/issues/189.
And thanks to @yi-Xu-0100 to create the issue.
