### ISSUE TITLE
[FEAT]Can support custom type of committing change? 

### ISSUE THREAD

**Issue by abcdGJJ** [vivaxy/vscode-conventional-commits#16]
**Describe the solution you'd like**
Now I can only choose type one of feat,fix,docs... Can support custom type?

**Comment by vivaxy** [comment]
How about making commit types configurable in VSCode preferences?

**Comment by abcdGJJ** [comment]
> How about making commit types configurable in VSCode preferences?

I think write a config file in project may be better, becaese we can commit to github include my config file. Or if you can read commitlint.config.js file's type-enum rule? I saw your source code don't use this rule. But I don't know where commiting type description come form.

**Comment by vivaxy** [comment]
> > How about making commit types configurable in VSCode preferences?
> 
> I think write a config file in project may be better, becaese we can commit to github include my config file. Or if you can read commitlint.config.js file's type-enum rule? I saw your source code don't use this rule. But I don't know where commiting type description come form.

[`type-enum`](https://commitlint.js.org/#/reference-rules?id=type-enum) is great.
