### ISSUE TITLE
[BUG] Missing icon after VSCode update 1.56

### ISSUE THREAD

**Issue by deoomen** [vivaxy/vscode-conventional-commits#160]
### Describe the bug

After last VSCode update which changes icons, Conventional Commits plugin icon is also not rendering correctly. There is only a few pixels in heigh where you can click on it.

### To reproduce

1. Update VSCode to 1.56.
2. Install Conventional Commits plugin.
3. Go to `Source Control` tab.
4. See missing icon (only little lighter small dot instead icon).

### Expected behavior

Default Conventional Commits plugin icon should be rendered.

### Screenshots

![image](https://user-images.githubusercontent.com/6989706/117784589-049f4880-b244-11eb-9668-1abf6f2b6377.png)
![image](https://user-images.githubusercontent.com/6989706/117785278-b6d71000-b244-11eb-9922-e5af29eb7889.png)

### Application logs

```
[info] Extension Activated
[info] vscode.env.language: en
[info] last used version: 1.21.0
[info] Conventional commits started.
[info] VSCode version: 1.56.0
[info] Git version: 1.0.0
[info] VSCode Conventional Commits version: 1.21.0
[info] conventionalCommits.autoCommit: true
[info] conventionalCommits.emojiFormat: code
[info] conventionalCommits.gitmoji: true
[info] conventionalCommits.lineBreak: 
[info] conventionalCommits.promptBody: true
[info] conventionalCommits.promptFooter: true
[info] conventionalCommits.promptScopes: true
[info] conventionalCommits.showEditor: false
[info] conventionalCommits.showNewVersionNotes: true
[info] conventionalCommits.editor.keepAfterSave: false
[info] git.enableSmartCommit: false
[info] git.smartCommitChanges: all
[info] git.postCommitCommand: none
```

[troubleshooting]: https://github.com/vivaxy/vscode-conventional-commits#troubleshooting

**Comment by deoomen** [comment]
Ubuntu 20.04.2 LTS

**Comment by aleexnl** [comment]
Same issue on MacOS Big Sur 11.3.1 With Visual Studio Code 1.56.1
![image](https://user-images.githubusercontent.com/50357555/118095748-bec3bb00-b3d0-11eb-8d89-d7044e0d3de0.png)

**Comment by yi-Xu-0100** [comment]
👋 @deoomen @aleexnl I don't think it's an extension issue. I think it's related to VS Code (https://github.com/microsoft/vscode/issues/123041). Our icon complies with [VS Code's guidelines](https://code.visualstudio.com/api/references/contribution-points#Command-icon-specifications) (16px SVG icon). I think we should wait for the new version to update to see whether there are similar issues afterward or not. 😅

**Comment by aleexnl** [comment]
Oh ok, for me issue is closed. Thanks for the help!

**Comment by deoomen** [comment]
After updating VSCode to 1.56.2 icon render properly. I close issue.

![obraz](https://user-images.githubusercontent.com/6989706/118240798-b2586480-b49b-11eb-8c1d-46666fcb864f.png)
![obraz](https://user-images.githubusercontent.com/6989706/118240846-c00dea00-b49b-11eb-9614-0a27193f1746.png)
