### ISSUE TITLE
[FEAT] : Publish the extension to the Open VSX Registry

### ISSUE THREAD

**Issue by l0u1sg** [vivaxy/vscode-conventional-commits#163]
Hello,

I think it would be interesting to publish your wonderful extension in the VSX Registry. This will allow people using GitPod, or Code-Serve, to use your extension in their browser... What do you think about it ?

**Comment by mhkb** [comment]
One upvote here, since it would be great to be able to also use this with VSCodium.

**Comment by l0u1sg** [comment]
Yes I think it could be a good idea

**Comment by yi-Xu-0100** [comment]
@vivaxy According to the [official document](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions), I make a pr for this change, but it will need one new token as `secrets.OPEN_VSX_TOKEN` for publishing to openvsx. Wait for your decision and help! 😀

**Comment by l0u1sg** [comment]
I will look into how to generate one

**Comment by l0u1sg** [comment]
I had a quick look, it's actually quite simple, I'll clone the branch you made and try to deploy the extension

**Comment by l0u1sg** [comment]
Ah I didn't see, you already added the necessary steps to publish in Open VSX Registry. So all that's left to do is merge

**Comment by vivaxy** [comment]
Thank you for your suggestions!
VSCode Conventional Commits is now available on Open VSX: https://open-vsx.org/extension/vivaxy/vscode-conventional-commits
