### ISSUE TITLE
[FEAT]An option to set the gitmoji position

### ISSUE THREAD

**Issue by eallion** [vivaxy/vscode-conventional-commits#171]
### Is your feature request related to a problem? Please describe

Ya, I think it's a problem for me and my team.

### Describe the solution you'd like

Put emoji at the beginning of the commit message.

### Describe alternatives you've considered

An option to set the gitmoji position

### Additional context

![屏幕截图 2021-06-29 223956](https://user-images.githubusercontent.com/1698841/123818609-b6492480-d92b-11eb-952d-cfd47402e1b7.png)

Thanks very much!

**Comment by yi-Xu-0100** [comment]
👋 @eallion, thanks for your advice, but this format seems does not fit with the [comventional commit](https://www.conventionalcommits.org/en/v1.0.0/), could it recognize by any changelog generator? What will show in the changelog generator you found?

**Comment by eallion** [comment]
Only one issue talk about gitmoji in `comventional commit`: https://github.com/conventional-commits/conventionalcommits.org/issues/41 , and I have seen many projects using gitmoji in their commit message. Some people like to put it at the beginning of the commit message, some people don't. But the gitmoji official repo is the former: https://github.com/carloscuesta/gitmoji . Most of the VSCode marketplace are former too.

![11](https://user-images.githubusercontent.com/1698841/123921637-cd365800-d9b9-11eb-9283-2eb0884ea4fb.gif)

So I just suggest to make an option(to set yourself style), this will be neater.

**Comment by eallion** [comment]
Another reason is that auto generate changelog easier.

**Comment by yi-Xu-0100** [comment]
@eallion I investigate the commit format before, and here are some personal opinions about the `gitmoji` usage.

1. For the [gitmoji](https://github.com/carloscuesta/gitmoji), It uses the `emoji` to replace the `type` of [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/). In [its git history](https://github.com/carloscuesta/gitmoji/commits/master), It is not fit the format of the conventional commit. If we use the emoji before the commit message, it will break the format of conventional commit and seems to repeatedly emphasize the type.

2. If we want to use the conventional commit format, the main reason is to use the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) or other tools like [standard-version](https://github.com/conventional-changelog/standard-version) to generate a good changelog. By the way, which tools you used to generate the changelog?

3. In my own opinion, the `conventional-changelog` format, the plain log looks very unattractive, so add `emoji` to the description of commit to increase the viewing and improve the ability to distinguish between entries of the same type. The format used now can both make changelog looks well and fit with the `standard-version` tool.

Finally, for this extension, I think it should maintain the format of the conventional commit. And maybe the [commitzen](https://github.com/KnisterPeter/vscode-commitizen) will helpful for your usage. If you want to add this feature as an option, welcome to make a PR or wait for the possible version. It may be not a necessary or urgent option by now, and I have no enough time to make a contribution.

**Comment by eallion** [comment]
Thanks for you share.
