### ISSUE TITLE
Line break

### ISSUE THREAD

**Issue by seloner** [vivaxy/vscode-conventional-commits#175]
I have picked \n for line break . It does work but how to remove the empty space after the new line .
with this line 1 \n line 2
I get 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/29483115/125752275-3210c48d-306c-4e64-9183-ed2af03e741b.png">

**Comment by vivaxy** [comment]
Please try type `line 1\nline 2`.

**Comment by seloner** [comment]
Yes  it worked
I was trying with line 1 \nline 2 but that didn't work also
Anyway thanks
