### ISSUE TITLE
[BUG] Emoji codes don't work with anything besides GitHub

### ISSUE THREAD

**Issue by ggondim** [vivaxy/vscode-conventional-commits#19]
The extension supports git emojis but adds them as emoji codes, not as Unicode characters. This only works in GitHub and GitLab, other Git providers like [Azure DevOps does not support them](https://developercommunity.visualstudio.com/idea/805609/gitmoji-support.html).

![image](https://user-images.githubusercontent.com/2074685/86553420-1546aa00-bf21-11ea-8ee5-0dce220ec2e1.png)

Also, even the most basic usage of commit descriptions (**git log in terminal**) does not support emoji codes:

![image](https://user-images.githubusercontent.com/2074685/86553161-525e6c80-bf20-11ea-8cdc-0c87d322a33b.png)

The only workaround for it is to mannualy edit the commit message and replace it by corresponding emoji as Unicode.

Highlights:
-  **[gitmoji-cli supports configuration to choose from emojicodes or Unicode](https://github.com/carloscuesta/gitmoji-cli/blob/master/src/commands/config/prompts.js#L11)**
-  **[rumoji](https://github.com/mwunsch/rumoji) encodes/decodes emoji codes and could be useful to fix this problem**

The only advanced workaround I think for it is to create a `commit-msg` hook and convert the codes to characters using rumoji.

**Comment by vivaxy** [comment]
Thanks for your suggestion. I'll try to add a `emojiFormat` option to provide a way to config it.
