### ISSUE TITLE
[FEAT] Default `activeItem` to be the top choice

### ISSUE THREAD

**Issue by toddlerer** [vivaxy/vscode-conventional-commits#190]
### Is your feature request related to a problem? Please describe

When using the keyboard only to control `QuickPick`, it is tedious to press <kbd>↓</kbd> and then <kbd>Enter</kbd>, especially to select None.

### Describe the solution you'd like

I want the default `activeItem` to be the top choice.

### Describe alternatives you've considered

I thought that I should make the default `activeItem` the top choice only for scope and gitmoji questions with None, but since it would reduce the number of keyboard entries by at most one, I thought it would be better to make it the same for all other `QuickPick` cases.

### Additional context

If agreed to this feature request, I can implement this feature and send a pull request.

**Comment by yi-Xu-0100** [comment]
I think that it is a good feature fro full keyboard user. 👍
