### ISSUE TITLE
[FEAT] Option to not focus scm panel with auto commit

### ISSUE THREAD

**Issue by barklan** [vivaxy/vscode-conventional-commits#201]
### Is your feature request related to a problem? Please describe

It is a little inconvenient that with auto commit enabled the source control panel gets focused after every commit. I almost always press to restore explorer panel. 

### Describe the solution you'd like

**Done in #200** (without Chinese localization).

Added `silentAutoCommit` option. When enabled the auto commit happens without focusing source control panel. The rest of behavior is the same. Please review. 

### Describe alternatives you've considered

...

### Additional context

Thanks for the great extension. Saves a lot of time compared to cli alternatives.

**Comment by yi-Xu-0100** [comment]
close in #200
