### ISSUE TITLE
[FEAT] Add skip ci feature

### ISSUE THREAD

**Issue by nenadfilipovic** [vivaxy/vscode-conventional-commits#212]
### Is your feature request related to a problem? Please describe

User can tell GitHub actions to skip running workflow by typing `[skip ci]` in commit title, it would be nice that extension ask user should CI be skipped.

### Describe the solution you'd like

It should add `[skip ci]` to commit title in GitHub actions case, it could also offer to choose which platform user uses and apply accordingly.

`After checking I think all CI systems use [skip ci]` so it would be safe to use that, I am still not sure can it be used only in title or in body as well.

### Describe alternatives you've considered

I usually just manually write it in title.

### Additional context

Skip builds on specific CI systems:
https://www.scivision.dev/skip-ci-builds-git-commit/

**Comment by vivaxy** [comment]
Thank you for your feedback.

For now, `[skip ci]` can be added manually in the commit message box, if the `autoCommit` option is off.

**Comment by nenadfilipovic** [comment]
Would you accept PR with this feature maybe?

**Comment by vivaxy** [comment]
@nenadfilipovic Which PR extactly?

**Comment by nenadfilipovic** [comment]
If I build PR with this feature, would you accept it?

**Comment by vivaxy** [comment]
@nenadfilipovic PR is welcomed.

**Comment by nenadfilipovic** [comment]
@vivaxy please check when you can #213
