### ISSUE TITLE
[FEAT] Allow Multiple line on the description

### ISSUE THREAD

**Issue by AxoCode** [vivaxy/vscode-conventional-commits#219]
### Is your feature request related to a problem? Please describe

Whenever I want to have multiple line at the description, I have to cancel the commit first, and edit the description

### Describe the solution you'd like

Allow entering a line by using probably `Shift` + `Enter`

**Comment by yi-Xu-0100** [comment]
👋 @AxoCode, Thanks for your question, I think it can be solved by adding a `lineBreak`. 🧐

See in https://github.com/vivaxy/vscode-conventional-commits#faq

**Comment by AxoCode** [comment]
Ah, sorry. I dont see that

**Comment by AxoCode** [comment]
![image](https://user-images.githubusercontent.com/57800056/147871615-37d6e48b-eba7-43b6-a5ad-38da99f85480.png)
wait is that color new lmao
