### ISSUE TITLE
[FEAT] don't open Source Control pane (if closed) on commit

### ISSUE THREAD

**Issue by ahinkle** [vivaxy/vscode-conventional-commits#230]
### Is your feature request related to a problem? Please describe

One thing that is a small distraction is that once I make a commit using this extension my "Source Control" tray opens. I didn't have it open on commit. If I don't use this extension and use the built-in Git commit via command palette it doesn't open my source control tray.

### Describe the solution you'd like

Make a commit with this extension
If the source control window is closed, don't open it.

### Additional context
on commit, opens this panel:
![Screen Shot 2022-02-21 at 1 53 02 PM](https://user-images.githubusercontent.com/17038330/155019041-546d86a8-716f-4e70-9865-acfc4e2006f7.png)

**Comment by yi-Xu-0100** [comment]
👋 @ahinkle, try to set `conventionalCommits.silentAutoCommit` as `true`.
