### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by RuizuKun-Dev** [vivaxy/vscode-conventional-commits#234]
### Is your feature request related to a problem? Please describe

- would be nice to have an option to put emoji before commit type i.e: 
⭐️feat (scope): short 
long description 
!breaking changes

### Describe the solution you'd like

- add an option to put emoji before or after commit type

**Comment by yi-Xu-0100** [comment]
👋 @RuizuKun-Dev, thanks for your advice, I think it does not fit with the format of conventional-commits. 

See more discussion in issue #171. 😁
