### ISSUE TITLE
Extension icon is invisible after VSCode update v1.40

### ISSUE THREAD

**Issue by creage** [vivaxy/vscode-conventional-commits#24]
**Describe the bug**
Extension icon (pink circle) is not visible in latest VSCode, clicking on the icon space works fine though.

**To reproduce**
1. Install latest VSCode
2. Install latest VSCode Conventional Commits extension
3. Open Source Control view
4. No icon is visible on the pane header

**Expected behavior**
Icon should be visible - right?

**Screenshots**

![image](https://user-images.githubusercontent.com/910967/87471896-60e30d00-c61f-11ea-8e66-62348cc34d23.png)

**Comment by vivaxy** [comment]
Thank you for your feedback. Problem confirmed.

Maybe it's related to the icon size or the `background-size` style property.

**Comment by vivaxy** [comment]
Fixed in https://github.com/vivaxy/vscode-conventional-commits/commit/0507aa96bfd4d9836955a1884dd5cf275e06c6c6.
