### ISSUE TITLE
[BUG] Gitmojis not searchable by name when format is set to Emoji

### ISSUE THREAD

**Issue by Jak-Ch-ll** [vivaxy/vscode-conventional-commits#240]
### Describe the bug

The Gitmojis are not searchable by name when the **emojiFormat** is set to **emoji**

### To reproduce

1. Set **emojiFormat** to **emoji**
2. Start a conventional commit via the extension
3. At the emoji step search for a Gitmoji name (e.g. *white_check_box*)
4. The Gitmoji for white_check_box is not shown

### Expected behavior

The Gitmojis should be searchable by name, the same as when emojiFormat is set to *code*

### Screenshots

Format set to emoji:
![image](https://user-images.githubusercontent.com/56225668/164432335-100f5da2-e168-40ba-933d-d6229fedc9c1.png)

Format set to code:
![image](https://user-images.githubusercontent.com/56225668/164432791-7122d01f-69c8-40e1-890f-7f94be3f4e5b.png)

### Application logs

Follow the [troubleshooting] section and paste the logs here.

[troubleshooting]: https://github.com/vivaxy/vscode-conventional-commits#troubleshooting

**Comment by Jak-Ch-ll** [comment]
Hi @yi-Xu-0100,
I tested the version and it indeed works as expected. Thank you for the quick fix! 👍

**Comment by yi-Xu-0100** [comment]
There is a problem with the automatic release process, this issue is temporarily reserved, and the beta version of the extension can be used for a long time until the new version is released. 😅

**Comment by vivaxy** [comment]
v1.24.1 is released
