### ISSUE TITLE
[FEAT] Configure subject length

### ISSUE THREAD

**Issue by ghiscoding** [vivaxy/vscode-conventional-commits#25]
**Is your feature request related to a problem? Please describe.**
Typed a description that was too long and GitHub split it into 2 lines with (...) on 2nd line

**Describe the solution you'd like**
Would be nice to have a config with max

**Describe alternatives you've considered**
I don't know of any alternatives

**Additional context**
VSCode already has this setting `Git: Input Validation Subject Length` that we can configure. 
![image](https://user-images.githubusercontent.com/643976/87838835-4babef80-c866-11ea-9840-42dc56100c34.png)

and the Commitizen VSCode plugin also have a similar setting 
![image](https://user-images.githubusercontent.com/643976/87838869-68482780-c866-11ea-94fc-5f9b7587b0f0.png)

So it would be really nice if this great plugin also include such setting or use the default VSCode setting. 
It would be helpful to know when we reach the length limit so that we don't end up having it split

Thank you for the great plugin, work as expected, this would just make it more awesome 😄

**Comment by vivaxy** [comment]
@ghiscoding Hi, thank you for you question.
You can try to add a [commitlint config](https://commitlint.js.org/#/reference-configuration) in your project. It provides rules like [subject-max-length](https://commitlint.js.org/#/reference-rules?id=subject-max-length).

**Comment by ghiscoding** [comment]
@vivaxy 
ohh sorry I did not see that part of your readme, however if I understand correctly this seem to require `@commitlint/cli` and then a `./commitlint.config.js` file. Did I understand correctly? 

I was hoping to set a max subject length without installing anything (apart from the plugin) and just configure it through the VScode settings. I actually chose your plugin over the other popular commitizen VSCode plugin because it won't work at all without installing any lib. 

Subject length is the only config I'm missing for this to work as a standalone plugin? 
Do you have any other suggestions?

**Comment by vivaxy** [comment]
Hi, @ghiscoding 

`vscode-conventional-commits` reads `./commitlint.config.js` without any extra lib.

`@commitlint/cli` is required when you'd like to use `commitlint` in the CLI.
