### ISSUE TITLE
Question: Is better to use code or gitmoji for emoji format?

### ISSUE THREAD

**Issue by AnzhiZhang** [vivaxy/vscode-conventional-commits#252]
I found that there are two formats of Emoji Format in settings. One is `code` and one is `gitmoji`.

![image](https://user-images.githubusercontent.com/37402126/172625078-9b28d68a-63f2-4782-8a02-4568657b5fde.png)

I searched issues and read the doc, I could not find any useful info about the differences between them. Which is the better one to use, is there any potential incompatibility for any format?

Thanks for your help!

**Comment by yi-Xu-0100** [comment]
👋 @AnzhiZhang , The `emoji` means the word will use Unicode characters like 🐛. The `code` will use the `:bug:`. The latter will display as emoji in GitHub, but in the git log, it is the code actually.

For my usage, the `code` displays well most time and is searchable, but it will expand the length of the commit message. On the contrary，the `emoji` display will fully support the log display and reduce the characters, but it is hard to be searched.

In the [gitmoji](https://gitmoji.dev/), you can see most of the correspondence between code and emoji. 😁
