### ISSUE TITLE
[FEAT] Emoji location option

### ISSUE THREAD

**Issue by Javinyx** [vivaxy/vscode-conventional-commits#254]
### Is your feature request related to a problem? Please describe

Emoji location is after commit type by default right now.

### Describe the solution you'd like

Being able to add emoji before the whole commit message.

### Additional context

Right now, it's like this by default:
`feat: ✨ new feature`

Having this option could make it like this:
`✨ feat: new feature`

Thanks for reading!

**Comment by yi-Xu-0100** [comment]
👋 @Javinyx, Thanks for your question, The discussion in #171 may be helpful.

**Comment by Javinyx** [comment]
@yi-Xu-0100 Thank you!
