### ISSUE TITLE
(nearly exact) Copy of "Conventional Commits" VSCode extension on the marketplace

### ISSUE THREAD

**Issue by mcanouil** [vivaxy/vscode-conventional-commits#264]
A nearly exact copy (one commit) of the extension is on the marketplace which might confuse users, especially since the links point to this repository.
VSCode extension: https://marketplace.visualstudio.com/items?itemName=Dowen.vscode-conventional-commits-bts
Repository: https://github.com/Tokenyet/vscode-conventional-commits

**Comment by vivaxy** [comment]
Thanks for the notice @mcanouil. I've emailed the author.

**Comment by vivaxy** [comment]
@mcanouil Thanks to the author of [marketplace.visualstudio.com/items?itemName=Dowen.vscode-conventional-commits-bts](https://marketplace.visualstudio.com/items?itemName=Dowen.vscode-conventional-commits-bts). The extension had changed: icon, name, readme, links. I think there is no other confusions. Issue closed.
