### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pedromdsn** [vivaxy/vscode-conventional-commits#269]
### Describe the bug

Does not open the menu.

### To reproduce

When I click ctrl + shift + p and click on the conventional commits vscode says `Activating extensions` when finished the menu still doesn't open.
I'm using w11 and wsl with ubuntu 20.04.
No problems until the last update.

### Screenshots

![image](https://user-images.githubusercontent.com/57453260/193434754-c096f5f3-3fb7-4507-85ac-8b5bdfd33f5e.png)

### Application logs
```

[info] Extension Activated
[info] vscode.env.language: pt-br
[warning] getNLS: Missing translation for pt-br
[info] last used version: 1.24.2
```

**Comment by yi-Xu-0100** [comment]
👋 @Pedromdsn, What version of VS Code are you currently using?

**Comment by Pedromdsn** [comment]
Last.

**Comment by yi-Xu-0100** [comment]
@Pedromdsn I mean the version of VS Code, not the version of extension.

**Comment by Pedromdsn** [comment]
![image](https://user-images.githubusercontent.com/57453260/193545102-5e86ad55-9355-466b-9b43-ce57929ad756.png)

**Comment by Pedromdsn** [comment]
I managed to solve.

Solution:
I formatted the PC and it fixed it.
