### ISSUE TITLE
[FEAT] About the icon

### ISSUE THREAD

**Issue by fuzuyx** [vivaxy/vscode-conventional-commits#27]
**Is your feature request related to a problem? Please describe.**
I'm really sorry on this personal preferences but the icon frustrate me lol.

**Describe the solution you'd like**
Maybe change the icon into the one that has the same design language as Microsoft's own [codicon](https://microsoft.github.io/vscode-codicons/dist/codicon.html)?

**Describe alternatives you've considered**
Or remove that red circle button on the "Source Control" toolbar?

**Additional context**
![image](https://user-images.githubusercontent.com/18055365/90386379-aecfb280-e0ae-11ea-8d37-4d08dfbf1f45.png)

PS. I would love to do some PR on this. Thank You!

**Comment by vivaxy** [comment]
🤔 Would be nice if icon looks like codicon. And how do codicon adapt to the editor themes?
