### ISSUE TITLE
[BUG] How to close if you dont want to commit

### ISSUE THREAD

**Issue by Gustav-Eikaas** [vivaxy/vscode-conventional-commits#274]
### Describe the bug
There is no close button in-case you don't want to commit.
![image](https://user-images.githubusercontent.com/89254170/196153941-9e1551e8-6344-4bef-9e71-7ff9e92b2071.png)

### To reproduce
1. Press the circle on git tab to open the wizard

### Application logs

Follow the [troubleshooting] section and paste the logs here.

[troubleshooting]: https://github.com/vivaxy/vscode-conventional-commits#troubleshooting

**Comment by yi-Xu-0100** [comment]
👋 @Gustav-Eikaas, The `Esc` may helpful to cancel the operation.
