### ISSUE TITLE
[BUG] Conventional Commits: Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by YXL76** [vivaxy/vscode-conventional-commits#282]
### Describe the bug

Excuting `extension.conventionalCommits` failed.

https://github.com/vivaxy/vscode-conventional-commits/blob/18193e87241be70ae6782b8396a8ef9685ff7fa8/src/lib/conventional-commits.ts#L38-L48

`arg` is `{ "w": "git", "x": "Git", "g": 2, "j": "", "q": true, "t": 0 }`, no `_rootUri` in it.

### Environment

Version: 1.74.0-insider (system setup)
Commit: 1b1e2a2c5794df1f475976062c754651827634a9
Date: 2022-11-18T05:25:18.342Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by unlsycn** [comment]
the same problem.

**Comment by melMass** [comment]
Same issue, tried on both mac and windows.
Running from the command palette works, I disable extensions auto update as it's not the first time I have an extension that stops working mid project.

**Comment by YXL76** [comment]
The type should be `vscode.Uri | undefined`?
Will change `const _arg = arg?._rootUri.fsPath;` to `const _arg = arg?._rootUri?.fsPath;` break something? It works fine for me.

**Comment by yi-Xu-0100** [comment]
@YXL76 Do you mean to change these two contents?

```diff
-   _rootUri: vscode.Uri; 
+   _rootUri: vscode.Uri | undefined; 

...

-   const _arg = arg?._rootUri.fsPath;
+   const _arg = arg?._rootUri?.fsPath;
```

**Comment by YXL76** [comment]
> @YXL76 Do you mean to change these two contents?
> 
> ```diff
> -   _rootUri: vscode.Uri; 
> +   _rootUri: vscode.Uri | undefined; 
> 
> ...
> 
> -   const _arg = arg?._rootUri.fsPath;
> +   const _arg = arg?._rootUri?.fsPath;
> ```

yes

**Comment by yi-Xu-0100** [comment]
@YXL76 Would you be willing to submit a PR to fix this issue and I'll let the action execute to generate a beta version for testing? 😊

**Comment by yi-Xu-0100** [comment]
Thanks @YXL76 , @melMass @unlsycn Try the beta extension to check it. 😊

- https://github.com/vivaxy/vscode-conventional-commits/actions/runs/3537577440#artifacts

**Comment by unlsycn** [comment]
> Thanks @YXL76 , @melMass @unlsycn Try the beta extension to check it. 😊
> 
> * https://github.com/vivaxy/vscode-conventional-commits/actions/runs/3537577440#artifacts

It seems work fine thx

**Comment by Alfian5229** [comment]
so when its going live?

**Comment by yi-Xu-0100** [comment]
@Alfian5229 If there is no other problem about it, it will be release on this friday. 😊

**Comment by melMass** [comment]
Works fine for me too!
waiting for the release 🚀

**Comment by yi-Xu-0100** [comment]
All subscribers, a new version that fixes this issue has been released~ 😁
