### ISSUE TITLE
[BUG] commitlint.config.js gets ignored

### ISSUE THREAD

**Issue by Starraider** [vivaxy/vscode-conventional-commits#29]
**Describe the bug**

My commitlint.config.js gets ignored. 

Maybe you can provide a sample file how the commitlint.config.js has to look like to make it work?

**To reproduce**

1. Install extension
2. Restart VS Code
3. Make new commitlint.config.js
4. Add some rules
5. Test commit

Here you can find my [commitlint.config.js](https://github.com/Starraider/devTypo3ddev/blob/master/commitlint.config.js)

**Expected behavior**

My type-enums should be displayed, but they are not.

**Application logs**

```
Started
VSCode version: 1.49.0-insider
VSCode Conventional Commits version: 1.11.0
Git version: 1.0.0
autoCommit: true
gitmoji: false
emojiFormat: code
scopes: deployer
lineBreak: 
git.enableSmartCommit: true
git.smartCommitChanges: all
git.postCommitCommand: sync
arg: /Users/sven/Documents/Projekte/devTypo3ddev
git.repositories: /Users/sven/Documents/Projekte/devTypo3ddev
workspacceFolders: /Users/sven/Documents/Projekte/devTypo3ddev
commitlintRuleConfigs: {}
commitMessage: {
  "type": "test",
  "scope": "",
  "gitmoji": "",
  "subject": "Fix commitlint.config.js",
  "body": "",
  "footer": ""
}
message: test: Fix commitlint.config.js
inputBox.value: test: Fix commitlint.config.js
Finished successfully.
```

**Comment by vivaxy** [comment]
1. Please make sure you have installed `@commitlint/config-conventional`.
2. Please make sure your commitlint config is valid. See [Commitlint Website](https://commitlint.js.org/#/reference-configuration?id=shareable-configuration).

**Comment by Starraider** [comment]
I don't understand. Where do I have to install `@commitlint/config-conventional`?
I'm using Visual Studio Code with your `vscode-conventional-commits` extension, but I want to change the type-enum.
I don't have a Node project. 

So where or how do I have to install `@commitlint/config-conventional`?

You write in your README: "Respect commitlint configs." So you don't read the `commitlint.config.js`?

**Comment by vivaxy** [comment]
You have to install `@commitlint/config-conventional` in your project or in global.
And your `commitlint.config.js` is not valid. Please read the [Commitlint docs](https://commitlint.js.org/#/reference-configuration?id=shareable-configuration).

By design, `vscode-conventional-commits` extension does not install commitlint configs. Because there are lots of configs and lots of versions. If you'd like to use commitlint, please at least follow the commitlint config specification.

**Comment by Starraider** [comment]
Ok, thanks for you explanation.
I installed `@commitlint/config-conventiona` and fixed my `commitlint.config.js` and and it works.

Unfortunately after every "type" you put a colon ":", which is against the [commit rules for TYPO3 projects](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/CommitMessage.html). Is it possible to get rid of the colon?

**Comment by vivaxy** [comment]
`vscode-conventional-commits` follows [Conventional Commits](https://www.conventionalcommits.org/) which is not compatible with [Commit Message rules for TYPO3 CMS](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/CommitMessage.html). Maybe you can try to find or build another extension. 😃
