### ISSUE TITLE
[BUG] validation for subject-max-length is not calculated the same as commitlint

### ISSUE THREAD

**Issue by j3ko** [vivaxy/vscode-conventional-commits#30]
**Describe the bug**

It seems like [commitlint](https://github.com/conventional-changelog/commitlint) calculates the `subject-max-length` flag by adding all the characters of the first line, including the type, scope and gitmoji characters.  When entering a subject, the character count for a custom `subject-max-length` is only validated against the subject text.

**To reproduce**

1. Add the following rule to the `.commitlintrc.js` config file: 
```
'subject-max-length': [2, 'always', 50]
```
2. Start a commit.
3. Select `build`
4. Select `None`
5. Select :rotating_light:`:rotating_light:`
6. Enter: `this subject is less than 50 characters - with error`
7. Remove ` - with error` from the text box to put the subject character count under 50 to proceed
8. Proceed with the commit with blank entries for the other fields

**Result**

commitlint errors out with the following:
```
Current branch is "develop".
⧗   input: build: :rotating_light: this subject is less than 50 characters
✖   subject must not be longer than 50 characters [subject-max-length]
```

**Expected behavior**

Length validation on the subject input field should take into account: `build: :rotating_light: ` and not allow the user to proceed.

**Package Info**
```
"@commitlint/cli": "9.1.2",
"@commitlint/config-conventional": "9.1.2",
```

**Comment by vivaxy** [comment]
Thank you for your feedback. I'll try to fix this.

**Comment by vivaxy** [comment]
Length lint error will display as:
![image](https://user-images.githubusercontent.com/4216856/91252275-dea64680-e78f-11ea-8c27-20e3802f1b3b.png)
