### ISSUE TITLE
[FEAT] Using with Husky

### ISSUE THREAD

**Issue by jonghyung-lee** [vivaxy/vscode-conventional-commits#306]
### Is your feature request related to a problem? Please describe
First of all, thank you for developing this good extension. It's very useful.

However, it would be better if one feature could be added.
It is a feature that allows to apply pre-commit hook through husky at the same time while using this extension.
I am using pre-commit hook using husky, but currently, hook is triggered normally only when I commit through CLI. 
If I commit through this extension, the hook will not be triggered. 

Is there any way already?

**Comment by vivaxy** [comment]
Hi, @jonghyung-lee. This extension use VSCode git extension under the hood.
Please check if VSCode git extension is able to run your pre-commit hook. Ref: `https://code.visualstudio.com/docs/sourcecontrol/overview#_commit`.

**Comment by jonghyung-lee** [comment]
Ok! I'll find the way! 
May I have to close this PR?

**Comment by vivaxy** [comment]
@jonghyung-lee Feel free to close this issue. You can reopen it when there are further questions.
