### ISSUE TITLE
[BUG] Description writing restrictions

### ISSUE THREAD

**Issue by yakovlevkll** [vivaxy/vscode-conventional-commits#309]
### Describe the bug

Greetings, after the last update, the rules for the part with the description have become tougher. To be more precise, it became impossible to start the description with a capital letter. Thus, the ability to use abbreviations and names at the beginning of a sentence, such as ESlint, JSON etc.

### To reproduce

Start building commit message with extension, get error message when trying to capitalize description

### Expected behavior

Ability to enter a message with a capital letter. 

### Application logs

Follow the [troubleshooting] section and paste the logs here.

[troubleshooting]: https://github.com/vivaxy/vscode-conventional-commits#troubleshooting

**Comment by vivaxy** [comment]
@yakovlevkll Hi, please check your commitlint config, e.g. `subject-case`.

**Comment by yakovlevkll** [comment]
My bad, didn't think these things could be related ☺️

Thanks for the quick response and and for the awesome project maintained!
