### ISSUE TITLE
[QUESTION] Ability to define / limit commit types

### ISSUE THREAD

**Issue by brady-sewall** [vivaxy/vscode-conventional-commits#330]
### Is your feature request related to a problem? Please describe

I don't think so

### Describe the solution you'd like

Does this extension allow for customizing / limiting commit types? For example, our build routine looks for the following:
- fix
- feat
- refactor
- perf
- style
- test
- build
- chore

### Describe alternatives you've considered

Commitlint.js looks like it has a [`type-enum`](https://commitlint.js.org/#/reference-rules?id=type-enum) feature, but I don't understand where to configure that for this extension.

### Additional context

I have Commitlint installed (not using Husky) and a commitlint.config.js file in the root of my repo.

This is the contents of my commitlint.config.js:
```javascript
module.exports = {
  extends: ['@commitlint/config-conventional', '@commitlint/parse'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'fix',
        'feat',
        'refactor',
        'perf',
        'style',
        'test',
        'build',
        'chore',
        'ci',
      ],
    ],
  },
};
```

**Comment by vivaxy** [comment]
Hi, @brady-sewall. This extension supports commitlint by reading commitlint config files.
The `type-enum` rule is supported. See [Readme](https://github.com/vivaxy/vscode-conventional-commits?tab=readme-ov-file#supported-commitlint-rules) for details.
