### ISSUE TITLE
[BUG] Github, emoji not showing well

### ISSUE THREAD

**Issue by tyki6** [vivaxy/vscode-conventional-commits#333]
Hello, 
Thanks for your amazing work, i got a bug, i think it's releated to github upgrade, but on github some emoji doesn't appear.
Regards

### Describe the bug
On github some emoji doesn't appear, it show :emoji:

### Screenshots
![image](https://github.com/vivaxy/vscode-conventional-commits/assets/57527739/3e0f164c-4c3e-48c4-8ebb-9a22e7551663)

**Comment by kanematsugaku** [comment]
Specifying "emoji" as the value for `emojiFormat` config might be a temporary solution.

> `conventionalCommits.emojiFormat`
> Specify which format will be shown in the gitmoji.
> default: "code"
>
> _https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits_

👇

`settings.json`
```json
{
  ...
  "conventionalCommits.emojiFormat": "emoji"
}
```
