### ISSUE TITLE
[FEAT] Store scopes in user settings

### ISSUE THREAD

**Issue by Hobart2967** [vivaxy/vscode-conventional-commits#335]
### Is your feature request related to a problem? Please describe

As I'm working across different projects using this extension, I'd love to see support for storing scopes in user settings area instead of workspace.

Also, I don't like polluting the committed, non-gitignored settings file with this information, as it can be shared globally throughout other ways.

### Describe the solution you'd like

I would love to see a setting that controls where scopes are stored.

### Describe alternatives you've considered

There are none.

**Comment by Hobart2967** [comment]
PR attached, merge appreciated :)

**Comment by Hobart2967** [comment]
Any updates on this?

**Comment by vivaxy** [comment]
Hi, @Hobart2967 Thanks for the suggestion and PR.
I'd like to merge this feature if the PR is ok.

**Comment by Hobart2967** [comment]
> Hi, @Hobart2967 Thanks for the suggestion and PR. I'd like to merge this feature if the PR is ok.

Hi @vivaxy , alright, will deal with your comments, thanks for the reply!

**Comment by Hobart2967** [comment]
Hi @vivaxy,

I'm done working in all your feedbacks - One point though: I am not capable to implement the translation updates for the mentioned fields in chinese. I can only offer English, German and some Dutch - That's the end of the list then :)

Would welcome your help with it!

**Comment by Hobart2967** [comment]
@vivaxy Unfortunately, there's build errors because of your PR feedback. It seems that your code is not compilable using strict mode. Should I fix these issues to a working state again?
