### ISSUE TITLE
[FEAT] short description input should limit the max length according to the setting "header-max-length"

### ISSUE THREAD

**Issue by Mark-Fenng** [vivaxy/vscode-conventional-commits#35]
short description input should limit the max length according to the setting "header-max-length"

**Describe the solution you'd like**
Add a max length limit to the input element or as least give users some prompt information.

![image](https://user-images.githubusercontent.com/27533910/98494183-4b04f200-2277-11eb-8e72-06f582b7289d.png)

**Comment by vivaxy** [comment]
Please provide more information.
1. The [output](https://github.com/vivaxy/vscode-conventional-commits#troubleshooting) information.
2. The minimum demo of the problem to reproduce the issue.

**Comment by Mark-Fenng** [comment]
This issue is a new feature request rather than a bug report

**Comment by vivaxy** [comment]
Yes, this extension supports commitlint.

Could you please check if your project has installed `@commitlint/config-conventional` as a dependency or dev-dependency?

Relevant issues: https://github.com/vivaxy/vscode-conventional-commits/issues/29.

**Comment by Mark-Fenng** [comment]
Sorry for my negligence, the extension can read my commitlint config now.
But it's not my point of this issue. 
I request a feature: "short description input should limit the max length according to the setting "header-max-length" and I still can type in over 100 words in the input element.
![image](https://user-images.githubusercontent.com/27533910/98641250-6bf84080-2366-11eb-9e32-8a3d8bde9012.png)

**Comment by vivaxy** [comment]
Thank you for your explanation. I'll look into it.

**Comment by vivaxy** [comment]
@Mark-Fenng Please try v1.13.0.

**Comment by Mark-Fenng** [comment]
@vivaxy Thank you! It works on v1.13.0!
