### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jtovarto** [vivaxy/vscode-conventional-commits#41]
[vivaxy.vscode-conventional-commits-unresponsive.cpuprofile.txt]
(https://github.com/vivaxy/vscode-conventional-commits/files/5897322/vivaxy.vscode-conventional-commits-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-conventional-commits`
- Extension Version: `1.13.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`e:\Users\Clixer\AppData\Local\Temp\vivaxy.vscode-conventional-commits-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by vivaxy** [comment]
@Johanso-dev Hi, thank you for your information. Could you please upload the `e:\Users\Clixer\AppData\Local\Temp\vivaxy.vscode-conventional-commits-unresponsive.cpuprofile.txt`?

**Comment by yi-Xu-0100** [comment]
>The problem is that there are too many, often little, files that all need to be read and loaded. Considering bundling your extension, e.g with https://webpack.js.org or https://rollupjs.org/. For the former there is a sample: https://github.com/Microsoft/vscode-extension-samples/tree/master/webpack-sample

According to the wiki of VS Code, I think this issue can be fixed after bundling the extension.

**Comment by yi-Xu-0100** [comment]
@jtovarto Try to use the beta version: [vscode-conventional-commits-58fde4d.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2244058650/artifacts/46606810).

**Comment by jtovarto** [comment]
works fine, thanks.

**Comment by yi-Xu-0100** [comment]
@jtovarto Thanks for your reply!

@vivaxy I use the beta version recently and worked with it for some days. I think the next version can be released if there is no more question about it. 😀
