### ISSUE TITLE
Option to disable scope prompt

### ISSUE THREAD

**Issue by sidharthramesh** [vivaxy/vscode-conventional-commits#43]
**Is your feature request related to a problem? Please describe.**
I do not use scopes in projects that are small.

**Describe the solution you'd like**
An option to disable scopes in the settings like for gitmoji by setting `conventionalCommits.gitmoji : false` would be greatly appreciated. Maybe `conventionalCommits.promptScopes`?

**Describe alternatives you've considered**
Pressing enter rapidly seems to be working for now.

**Comment by yi-Xu-0100** [comment]
@sidharthramesh I make a PR to fix this issue, try to use the beta extension - [`vscode-conventional-commits-bf1ce8b.vsix`](https://github.com/vivaxy/vscode-conventional-commits/suites/2307717121/artifacts/48429425)! 😀

**Comment by sidharthramesh** [comment]
@yi-Xu-0100 Thank you! I will check it out

**Comment by yi-Xu-0100** [comment]
@sidharthramesh If there are any issues about it, just reopen this issue and add a comment.
