### ISSUE TITLE
[BUG] '\n' not work for line break

### ISSUE THREAD

**Issue by yi-Xu-0100** [vivaxy/vscode-conventional-commits#46]
**Describe the bug**

When I set the conventionalCommits.lineBreak as '\n', it does not work for me.

**To reproduce**

1. win10 Professional 20H2
2. setting about conventionalCommits:
    ```json
    "conventionalCommits.autoCommit": false,
    "conventionalCommits.emojiFormat": "emoji",
    "conventionalCommits.lineBreak": "\n",
    ```

**Expected behavior**

Just like the readme says: `Set lineBreak configuration to \n. When you're typing, enter \n as a line break.`

**Screenshots**

![image](https://user-images.githubusercontent.com/25523606/107879278-d2b36a00-6f12-11eb-89f0-63b08c216f6f.png)

**Application logs**

```bash
Started
VSCode version: 1.53.2
VSCode Conventional Commits version: 1.13.0
Git version: 1.0.0
autoCommit: false
gitmoji: true
emojiFormat: emoji
scopes: 
lineBreak: 

git.enableSmartCommit: true
git.smartCommitChanges: all
git.postCommitCommand: none
arg: d:\4 Creation\github\repo-list-generator
git.repositories: d:\4 Creation\github\repo-list-generator
workspacceFolders: d:\4 Creation\github\repo-list-generator
commitlintRuleConfigs: {}
commitMessage: {
  "_type": "fix",
  "_scope": "",
  "_gitmoji": "🐛",
  "_subject": "test line break",
  "_body": "test\\ntest\\n",
  "_footer": "test\\ntest\\n"
}
message: fix: 🐛 test line break

test\ntest\n

test\ntest\n
inputBox.value: fix: 🐛 test line break

test\ntest\n

test\ntest\n
Finished successfully.
```

**Comment by yi-Xu-0100** [comment]
By now, I test the `"conventionalCommits.lineBreak": "\\n"`, and it works. Maybe we need to fix the README? Or this is a bug?

new log:
```bash
Started
VSCode version: 1.53.2
VSCode Conventional Commits version: 1.13.0
Git version: 1.0.0
autoCommit: false
gitmoji: true
emojiFormat: emoji
scopes: 
lineBreak: \n
git.enableSmartCommit: true
git.smartCommitChanges: all
git.postCommitCommand: none
arg: d:\4 Creation\github\repo-list-generator
git.repositories: d:\4 Creation\github\repo-list-generator
workspacceFolders: d:\4 Creation\github\repo-list-generator
commitlintRuleConfigs: {}
commitMessage: {
  "_type": "fix",
  "_scope": "",
  "_gitmoji": "🐛",
  "_subject": "test line break",
  "_body": "test\ntest",
  "_footer": "test1\ntest1"
}
message: fix: 🐛 test line break

test
test

test1
test1
inputBox.value: fix: 🐛 test line break

test
test

test1
test1
Finished successfully.
```

**Comment by vivaxy** [comment]
Hi, are you using settings in JSON format?

![image](https://user-images.githubusercontent.com/4216856/107896204-9c0c3c80-6f70-11eb-8245-6a1357172c6b.png)

Here is the `\n` in settings panel, and it works fine on MacOS.
![image](https://user-images.githubusercontent.com/4216856/107896171-81d25e80-6f70-11eb-926e-2a8ba33e435e.png)

**Comment by yi-Xu-0100** [comment]
@vivaxy Oh, I got it, set the `\n` in the settings panel equal to set the `\\n` in JSON format. Thanks! 😀

Maybe we can add additional suggestions in the README. 😅

**Comment by vivaxy** [comment]
@yi-Xu-0100 Thank you for your suggestion.
