### ISSUE TITLE
[FEAT] use conventional-commit-types-i18n to localize the types

### ISSUE THREAD

**Issue by yi-Xu-0100** [vivaxy/vscode-conventional-commits#47]
**Is your feature request related to a problem? Please describe.**

I found the conventional-commit-types description still not localized.

**Describe the solution you'd like**

I create a package [@yi-xu-0100/conventional-commit-types-i18n](https://github.com/yi-Xu-0100/conventional-commit-types-i18n) and may give you a favor.

**Describe alternatives you've considered**

I only creat the `zh-cn` and the `en` for the first publish, any dialogue about it can give here.

**Additional context**

This is my first npm package, and I try to make it useful. 😀

**Comment by vivaxy** [comment]
Is this just for the display or also for the git commit message?
If we introduce other languages into commit messages, will other tools, like standard-version support this?

**Comment by yi-Xu-0100** [comment]
@vivaxy It is just to replace the package [`conventional-commit-types`](https://www.npmjs.com/package/conventional-commit-types), I didn't change the title and the keyword of type, but **only localized the description**. So the commit message will display as the same as before.

![image](https://user-images.githubusercontent.com/25523606/108672577-4f4ed580-751d-11eb-8953-f97f3857d4cf.png)

I should localize both the title and description may make the display better.

**Comment by vivaxy** [comment]
@yi-Xu-0100 Thank you for your explanation. It's a cool feature. But, is it possible to make:
1. Both title and description are in localized language.
2. Exported function returns json instead of string.

**Comment by yi-Xu-0100** [comment]
@vivaxy I update the package to [`v1.3.0`](https://www.npmjs.com/package/@yi-xu-0100/conventional-commit-types-i18n) and two questions above have been fixed. 😀
