### ISSUE TITLE
[FEAT] use manually scope for commit

### ISSUE THREAD

**Issue by yi-Xu-0100** [vivaxy/vscode-conventional-commits#50]
**Is your feature request related to a problem? Please describe.**

When I make commit to another open-source project, I may use the scope but do not want to create a setting for workspace.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/25523606/108950821-daf16f00-76a1-11eb-9e5d-6eb41dfae837.png)

The scope typed here can be used for the current commit.

**Comment by yi-Xu-0100** [comment]
Or maybe add a selection for using scope without create config.

**Comment by vivaxy** [comment]
Is it possible to add the scope config into git ignore?

**Comment by yi-Xu-0100** [comment]
@vivaxy I do not want to add more config for the open-source project. It may be confused for the project owner.

**Comment by yi-Xu-0100** [comment]
@vivaxy If the project uses this extension in the future, it may need to find a bug for the gitignore configuration. 😋

**Comment by vivaxy** [comment]
This brings more freedom of writing messages, which may bring mess in message scopes. But it should be restricted with tools like `commitlint`.

Feature accepted.
