### ISSUE TITLE
[BUG] publish action failed

### ISSUE THREAD

**Issue by yi-Xu-0100** [vivaxy/vscode-conventional-commits#64]
See https://github.com/vivaxy/vscode-conventional-commits/runs/2082721472.

Maybe I need to move the step of `push commit` to the publishing. 😅

Could you test this step locally for setting the env?

The good news is the v1.16.1 will not appear in release. 😀

**Comment by vivaxy** [comment]
Sorry, I am not familiar with GitHub Actions. @yi-Xu-0100 Is there a way to test it locally?

**Comment by yi-Xu-0100** [comment]
@vivaxy I revert the commit bring from the actions. 😅

https://github.com/vivaxy/vscode-conventional-commits/blob/d0068f3237ffcc64e64785bb6f1df7cfafef4179/.github/workflows/release.yml#L43-L46

This step is about publishing, and it runs using the bash and with the env setting. 
All the steps using the `run` can run locally in bash. For the workflows, only the creating release can not test locally.

**Comment by vivaxy** [comment]
I am running `VSCE_PAT=MY_PERSONAL_ACCESS_TOKEN yarn deploy` locally. But it prompts for `Personal Access Token for publisher 'vivaxy'`. I'm not sure why it's not the same error in GitHub Actions. Maybe I'll add a new test GitHub Action to test only the publish step.

**Comment by vivaxy** [comment]
Tested to set Personal Access Token to have all access and permissions according to https://github.com/microsoft/vscode-vsce/issues/522. And Failed.

**Comment by yi-Xu-0100** [comment]
@vivaxy I think it fixed! See in https://github.com/vivaxy/vscode-conventional-commits/runs/2083187479

**Comment by yi-Xu-0100** [comment]
@vivaxy Work well in https://github.com/vivaxy/vscode-conventional-commits/runs/2083222983 😀

**Comment by vivaxy** [comment]
Reverted Personal Access Token scopes to only Read and Publish Marketplace.
![image](https://user-images.githubusercontent.com/4216856/110741599-eb901080-826f-11eb-91a5-4fe2f75bf5b2.png)
