### ISSUE TITLE
'Missing module' error notification

### ISSUE THREAD

**Issue by jhhughes** [vivaxy/vscode-conventional-commits#8]
Hi,

Not sure if I am missing something but this is the error notification I see when attempting to do a commit via the extension.

![image](https://user-images.githubusercontent.com/13724293/80783757-16c0c280-8bbe-11ea-9d94-ccbbc007464a.png)

**Comment by jhhughes** [comment]
Hmm okay, so I just noticed this on another extension I was looking at...not sure how I fix it on my end without installing npm locally. (I'm just making some small improvements to a fork and the builds get done on another machine)

![image](https://user-images.githubusercontent.com/13724293/80784399-483a8d80-8bc0-11ea-8ad9-f00070f3ff6c.png)

**Comment by vivaxy** [comment]
Please check if you have a commitlint config with `extends: ['@commitlint/config-conventional']`. If so, please ensure you have run `npm install`.

**Comment by vivaxy** [comment]
Fixed in https://github.com/vivaxy/vscode-conventional-commits/blob/master/CHANGELOG.md#141-2020-05-01.
